### ISSUE TITLE
[FEAT] dbt docs serve mermaid

### ISSUE THREAD

**Issue by mattiasthalen** [datnguye/dbterd#105]
**Is your feature request related to a problem? Please describe.**
Not a problem, more of an enhancement.

**Describe the solution you'd like**
Have it modify `manifest.json` to include the mermaid code into the docs.
It should probably be added as a description for all tables in the model.

**Comment by datnguye** [comment]
Thanks @mattiasthalen for raising the feat!

It makes sense with your request, and I really love to have it as soon as possible.
However I don't think this feature will be in-scope for this tool, `dbterd` (at least for now). As of now, my only suggestion is to raise an issue to https://github.com/dbt-labs/dbt-docs for the ERD enrichment instead. Or let's build the Python script helper to handle this stuff.

Looking forward to seeing your thoughts as further. Thanks!

For addtional info, dbt docs site seems not to support Mermaid (as a code) in markdown (https://github.com/dbt-labs/dbt-docs/issues/338). So the only way now is to render the images and attach them into the docs site (aka. modify `manifest.json`)
