### ISSUE TITLE
[BUG] dbt run-metadata doesn't work with -s exposure:exposure_name

### ISSUE THREAD

**Issue by RecMarkoL** [datnguye/dbterd#108]
**Describe the bug**
When running `dbterd run -s exposure:exposure_name` I get a diagram of models related to that exposure. Prior to this I've ran `dbt deps` and `dbt compile` locally.

When I configure the dbt Cloud connection and run `dbterd run-metadata -s exposure:exposure_name` it returns nothing. I've tried multiple different syntaxes on the exposure name but can't get it working.

**To Reproduce**

1. Configure dbt Cloud environment
2. Run `dbterd run-metadata -s exposure:exposure_name`

**Expected behavior**
Returns a dbml model based on dbt Cloud Discovery API which contains models related to the exposure defined

**Desktop (please complete the following information):**

- OS: MacOS

**Comment by datnguye** [comment]
Hi @RecMarkoL thanks for raising the issue. I will try to check it out asap assuming you’re using dbterd latest version, let me know otherwise 🙌

**Comment by RecMarkoL** [comment]
Yes, I'm using latest version of dbterd

**Comment by datnguye** [comment]
Thanks @RecMarkoL again! Confirmed it's a bug now 👍 

It was a missing of passing the `kwargs` onto the 'parse tables' function. It's fixed now and will be released as soon as PR merged and get available in 1.13.4

**Comment by datnguye** [comment]
[1.13.4](https://github.com/datnguye/dbterd/actions/runs/8999845296) should be released now! Please help to check it outm feel free to reopen this issue if it's still persisted. Thanks again!
