### ISSUE TITLE
[BUG] Could not find adapter algo test_relationship

### ISSUE THREAD

**Issue by Svendewaard** [datnguye/dbterd#110]
**Describe the bug**
This actually used to work before, but ever since we moved to dbt-cloud and getting the manifest from there, I can no longer manage to specify a custom name for relationship tests.

**To Reproduce**
1. Specify environment variables in .env file
2. In a Python script, load the variables
3. Run the command: 
dbterd run --dbt-cloud -s schema:MARTS --entity-name-format schema.table -a "test_relationship:(name:foreignKey|c_from:column_name|c_to:field)"
4. catalog.json and manifest.json are correctly loaded (status 200)
5. Error is produced:
Exception: Could not find adapter algo test_relationship:(name:foreignKey|c_from:column_name|c_to:field)!

**Expected behavior**
The DBML file is properly generated with all relationships.

**Desktop (please complete the following information):**

- OS: Windows
- `dbterd --version`'s output [e.g. 1.7.1]: 1.13.4
- Our dbt cloud is on 1.7.14

**Comment by datnguye** [comment]
1.13.5 is published now 👍 
Please help to check it out, feel free to reopen the issue if it's still persisted.

By the way, your command should be: 
```
dbterd run --dbt-cloud -s schema:MARTS --entity-name-format schema.table -a "test_relationship:(name:foreign_key|c_from:column_name|c_to:field)"
```
