### ISSUE TITLE
[FEAT] Disable use of double quotes in table name to display Schemas in dbdocs.io

### ISSUE THREAD

**Issue by Svendewaard** [datnguye/dbterd#113]
**Is your feature request related to a problem? Please describe:**
All tables are currently named using the --entity-name-format flag, e.g. schema.table
The names then get rendered in double quotes: Table "finance_cubes.invoices" { .... }
However, dbdocs does not recognize the schema name as being a schema; it simply takes the whole name as the name of the table:
![image](https://github.com/datnguye/dbterd/assets/114741215/92f48817-0ddd-4f7c-b3d5-bd0648a31f76)

**Describe the solution you'd like:**
An option to somehow remove the double quotes to allow dbdocs to recognize the schemas and display them as such in their visualization tool:
![image](https://github.com/datnguye/dbterd/assets/114741215/1e2e9be5-e043-4d36-b481-e6cf0c4e9a7c)

**Comment by datnguye** [comment]
It should be available with v1.14 [here](https://dbterd.datnguyen.de/1.14/nav/guide/cli-references.html#dbterd-run-omit-entity-name-quotes)
