### ISSUE TITLE
[FEAT] Leverage dbt Semantic Model for the ERD

### ISSUE THREAD

**Issue by b-per** [datnguye/dbterd#117]
**Is your feature request related to a problem? Please describe:**

When implementing the new dbt Semantic Layer with metricflow, we have the ability to define [entities](https://docs.getdbt.com/docs/build/entities) in our semantic modelling, telling metricflow how to join tables together.

**Describe the solution you'd like:**

It would be great if `dbterd` could consume this semantic layer configuration information in order to "discover" how tables relate to each other.

**Describe alternatives you've considered:**

Manually defining the joins in the models config, on top of having already defined entities

**Additional context:**

I might be interested in contributing to it if nobody else wants to try to add the feature

**Comment by datnguye** [comment]
Thanks @b-per for raising this! I like this idea, definitely it is a great addition to scan the semantic models configs instead of just the relationship tests.

At the moment, I don’t think I have capacity to deliver this feat soon, so marking `help_wanted` for now, you are more than welcome for creating the PR for this.

Thanks a lot 🙏

**Comment by datnguye** [comment]
Hi @b-per Do you have any updates on this? 
Since I have some availabilities now, I will look into this if you haven't, hence removing `help_wanted` label.

By the way, do you suggest any sample of dbt jaffle shop with implemented semantic layer, or similar.

Thanks

**Comment by b-per** [comment]
Hi! 

I haven't worked on it yet, no. [This repo](https://github.com/dbt-labs/jaffle-shop) is jaffle-shop with metrics and SL configured as well.

**Comment by datnguye** [comment]
This should be available in dbterd v1.16 now. See [docs](https://dbterd.datnguyen.de/1.16/nav/guide/targets/choose-algo.html).

Keep this issue open to support dbt Cloud.

**Comment by datnguye** [comment]
> Amazing! I will test it in the next few days!

Thanks, feel free to reopen this issue if you would find any issues 🙌
