### ISSUE TITLE
In ERD, you can choose to add different types of DBT (seed, model, source, snapshot).

### ISSUE THREAD

**Issue by yingyingqiqi** [datnguye/dbterd#13]
Please check: https://github.com/datnguye/dbterd/issues/3
currently supports only resource_type=model, we should optionally add different dbt types.

Similar to this scene: 
I want to give an example. All our raw layer data is saved to S3 and corresponding external tables are created in Snowflake. Shouldn't we also add resource_type = source to the ERD?

**Comment by datnguye** [comment]
Bump v1.0.0
