### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by marcNY** [datnguye/dbterd#23]
**Describe the bug**
When installing the softare using pip install upgrade I get the following error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hologram 0.0.15 requires jsonschema<4.0,>=3.0, but you have jsonschema 4.17.3 which is incompatible.

**To Reproduce**
1. Python version 3.10.8 dbt version 1.4.5
2. run `pip install dbterd --upgrade`

**Expected behavior**
installation without errors

**Comment by datnguye** [comment]
Hi @marcNY thanks for raising this up!
For the initial check, I think that looks like an issue with dbt core 1.4 top pin dependencies has been impacting to the 3rd party tools so far.

[dbt core 1.4.6](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.6) should resolve it. Can you try to upgrade your dbt to 1.4.6 now, and try the installation again. I will look into it deeper if it's sill persisted. Thanks

**Comment by datnguye** [comment]
Hi @marcNY just wanted to check if the issue was still happened?

**Comment by datnguye** [comment]
Closed as inactive
