### ISSUE TITLE
Cover all kinds of TABLE (seed, model, source, snapshot), currently supports only resource_type=model

### ISSUE THREAD

**Issue by datnguye** [datnguye/dbterd#3]

**Comment by datnguye** [comment]
Only models are make sense to be in ERD

**Comment by yingyingqiqi** [comment]
@datnguye ，Why" Only models are make sense to be in ERD ", I want to give an example. All our raw layer data is saved to S3 and corresponding external tables are created in Snowflake. Shouldn't we also add resource_type = source to the ERD?

**Comment by yingyingqiqi** [comment]
cc: @il-dat , https://github.com/datnguye/dbterd/issues/13
thx
