### ISSUE TITLE
Support for manifest.json v9 / dbt v1.5

### ISSUE THREAD

**Issue by whichwit** [datnguye/dbterd#38]
**Describe the bug**
`Error: Could not open file 'manifest.json': File manifest.json is corrupted, please rebuild`

**To Reproduce**
`dbterd run` with default settings

**Expected behavior**
Generation of target ERD script

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (WSL2)

**Additional context**
Not sure if this is an issue or a feature request. Using **dbt 1.5**, which bumps the manifest.json version to v9. If dbt 1.5 isn't supported yet, it will be helpful to list supported dbt or manifest.json version.

**Comment by datnguye** [comment]
Fixed in [1.2.1](https://pypi.org/project/dbterd/1.2.1/)
