### ISSUE TITLE
Support for manifest.json v10 / dbt v1.6

### ISSUE THREAD

**Issue by vitmrnavek** [datnguye/dbterd#43]
**Describe the bug**
Error: Could not open file 'manifest.json': File manifest.json is corrupted, please rebuild

**To Reproduce**
dbterd run -mv 10

**Expected behavior**
Generation of target ERD script

Desktop (please complete the following information):
OS: Ubuntu 22.04 (WSL2)

**Additional context**
Think this is similar type of issue as 
https://github.com/datnguye/dbterd/issues/38

**Comment by datnguye** [comment]
@vitmrnavek it should be good now in [v1.2.5](https://github.com/datnguye/dbterd/releases/tag/1.2.5)
