### ISSUE TITLE
[FEAT] Render ERD with the actual fully qualified tablename

### ISSUE THREAD

**Issue by dylan-murray** [datnguye/dbterd#54]
**Is your feature request related to a problem? Please describe.**

Currently the ERD generator will output the ERD with the name of the node within the dbt project, i.e. `model.project.name`. It would be nice if there was an option to render the ERD with the actual table name itself like `database.schema.table` or just `schema.table` instead of the name of the dbt node. Not everyone who views an ERD is involved with dbt development so the node names can throw people off.

**Describe the solution you'd like**
The ability to be able to output an ERD with the actual tablename instead of the dbt node name.

**Comment by datnguye** [comment]
Thanks @dylan-murray for another good request 👍 

I will work it this weekend, and initially the solution will looks like this:
```
dbterd run --entity-name-format resource,package,model # default
dbterd run --entity-name-format database,schema,table # with fqn of the physical tables
dbterd run --entity-name-format schema,table # with schema.table only
dbterd run --entity-name-format table # with table name only
```

Let me know what you think.
Thanks

**Comment by dylan-murray** [comment]
This looks great to me! Flexible for every use case. Thanks for tackling my ideas! 😄

**Comment by datnguye** [comment]
It should be done in [dbterd 1.7.0](https://github.com/datnguye/dbterd/releases/tag/1.7.0) now!
