### ISSUE TITLE
[FEAT] Use model description as "note" in DBML.

### ISSUE THREAD

**Issue by SvensonDW** [datnguye/dbterd#65]
**Is your feature request related to a problem? Please describe.**
All of my models have a description that describes what it is for and what it is not for. Also it tells limitations.

**Describe the solution you'd like**
To automatically use the "description" as the "note" in the generated DBML for dbdocs.io

**Describe alternatives you've considered**
Copying them manually but this is too much work.

**Additional context**
Example DBML from dbdocs:
![image](https://github.com/datnguye/dbterd/assets/44198697/6dc0bb43-bd92-42f2-93ac-ec929911bd77)

**Comment by datnguye** [comment]
Hi @SvensonDW Thanks for the feedback!
But I am surprised a bit with this one because it is already implemented.

Can’t you see the column description populated as note in dbml? If yes, please help to give more info to reproduce it.

Thanks a lot

**Comment by datnguye** [comment]
Ah please ignore if this is model level, and it makes sense to add it. It will be done shortly, stay tuned 🏃

**Comment by SvensonDW** [comment]
@datnguye  Yes for the model level, thanks so much! 😄

**Comment by datnguye** [comment]
@SvensonDW it should be available soon in [1.8.0](https://github.com/datnguye/dbterd/releases/tag/1.8.0) 🎉
