### ISSUE TITLE
[FEAT] Add options to omit columns from diagram

### ISSUE THREAD

**Issue by syou6162** [datnguye/dbterd#78]
**Is your feature request related to a problem? Please describe.**
The table of interest in the ER diagram we want to draw has a very large number of columns. The number of columns can be dozens, making it very difficult to see the relationships between tables in an ER diagram.

**Describe the solution you'd like**
Add an option to omit columns in the ER diagram to allow output of a diagram without columns. For example, mermaid can only draw relationships between tables.

- https://mermaid.js.org/syntax/entityRelationshipDiagram.html

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by datnguye** [comment]
Thanks @syou6162 for the new great PR again!

Not related to this issue, I am planning to get v1.10 soon, in about within next 2 weeks time. The RCs are:
- this new option
- new command for querying dbt Cloud Discovery API in #68 

Let me know if you would have any thing to add. Cheers!

**Comment by syou6162** [comment]
@datnguye Thanks for letting us know!

I am using BigQuery as my DWH. BigQuery sometimes has column types that contain `<` special characters such as `Struct<first_name string, last_name string>` or column names that contain `. ` special characters, such as `name.first_name` in column names. Unfortunately, mermaid has a problem rendering markdown with such special characters, and I would like to add a feature to replace them before outputting markdown.

I will send an issue and pull request later!
