### ISSUE TITLE
[FEAT] Expose Python APIs officially

### ISSUE THREAD

**Issue by datnguye** [datnguye/dbterd#83]
**Describe the solution you'd like**
Expose Python APIs officially

- API to get a whole ERD
  ```python
  from dbterd.api import DbtErd

  erd = DbtErd().get_erd()
  print("erd (dbml):", erd)

  erd = DbtErd(target="mermaid").get_erd()
  print("erd (mermaid):", erd)
  ```
- API to get model's ERD: this model +1 level connected nodes
  ```python
  from dbterd.api import DbtErd

  dim_prize_erd = DbtErd(target="mermaid").get_model_erd(
      node_unique_id="model.dbt_resto.dim_prize"
  )
  print("erd of dim_date (mermaid):", dim_prize_erd)
  ```

  Here is the output:

  ```mermaid
  erDiagram
    "MODEL.DBT_RESTO.DIM_PRIZE" {
      varchar prize_key
      nvarchar prize_name
      int prize_order
    }
    "MODEL.DBT_RESTO.FACT_RESULT" {
      varchar fact_result_key
      varchar box_key
      varchar prize_key
      date date_key
      int no_of_won
      float prize_value
      float prize_paid
      int is_prize_taken
    }
    "MODEL.DBT_RESTO.FACT_RESULT" }|--|| "MODEL.DBT_RESTO.DIM_PRIZE": prize_key
  ```

API docs will be generated by `pdoc` 👉 [beta site](https://dbterd.datnguyen.de/1.12-beta/api-docs/dbterd/api.html)
PS: Mainly to support `dbt docs generate`'s result with the ERD enrichment

Give me a 👍 if you think it should be available asap! Thanks

**Comment by syou6162** [comment]
Great idea! In fact, I'm writing a script to wrap dbterd for the same purpose in my work case, so I thought it would help many people like me.

However, I think that there are many cases (including my case) where I would like to customize the output to markdown, so I hope that the `dbterd run` currently provided will be maintained as it is.

**Comment by datnguye** [comment]
> Great idea! In fact, I'm writing a script to wrap dbterd for the same purpose in my work case, so I thought it would help many people like me.
> 
> However, I think that there are many cases (including my case) where I would like to customize the output to markdown, so I hope that the `dbterd run` currently provided will be maintained as it is.

Good point for the various of customizations. Maybe this would just support the Python API for that purpose only.

**Comment by datnguye** [comment]
https://dbterd.datnguyen.de/1.12-beta/api-docs/dbterd/api.html 

Python API docs site preview 👀

**Comment by datnguye** [comment]
Note for some enhancements after the first test of v1.12.0b1:

```
from dbterd.api import DbtErd

erd = DbtErd(artifacts_dir="./target", target="dbml").get_erd()
print("erd", erd[1])

print("===============")
print("===============")

orders_erd = DbtErd(artifacts_dir="./target", target="dbml").get_model_erd(node_unique_id="model.jaffle_shop.orders")
print("erd of orders", orders_erd[1])

# artifacts_dir = cwd/None/target
# target key error
# log hiding
```

**Comment by datnguye** [comment]
@syou6162 
1.12.0b2 should be available now. Do you want to test it out? Thanks 😃 

I will need some more testing before releasing the major 1.12.0 next week!
