### ISSUE TITLE
[BUG] --entity-name-format does not apply on refs

### ISSUE THREAD

**Issue by marvingeerken** [datnguye/dbterd#92]
**Describe the bug**
Hey @datnguye

On the `run-metadata` command I've been using the `--entity-name-format` flag.
It applies the format on the tables inside the output.dbml file. However it's not applied on the relationships.
Hence the dbml compiler like dbdocs complains that it cant find the respective tables.

**To Reproduce**

1. `dbterd run-metadata -o "./target/" --entity-name-format table`
2. `dbdocs build "./target/output.dbml"`

**Expected behavior**
Selected entity-name-format on Refs.

Thanks for looking into it!
Best, Marvin

**Comment by datnguye** [comment]
Thanks @marvingeerken for this finding! 🙌 

Let me work it out this weekend 🏃

**Comment by datnguye** [comment]
@marvingeerken It should be fixed now in [1.11.1](https://github.com/datnguye/dbterd/releases/tag/1.11.1) (or [1.10.2](https://github.com/datnguye/dbterd/releases/tag/1.10.2))!
