### ISSUE TITLE
[FEAT]  Make name of output file customizable through CLI argument

### ISSUE THREAD

**Issue by Thootje** [datnguye/dbterd#97]
**Is your feature request related to a problem? Please describe.**

For our usecase, we want to output 2 different ERD diagrams for 2 different sets of data models. These 2 usecases are however located in the same repository. Therefore, we want to setup a flow in which we execute 2 dbterd commands to generate 2 different DBML outputs. However, the name of the DBML output file is always output.dbml. (see: https://github.com/datnguye/dbterd/blob/a03af25c9efe9fe4f32208e4b1a2acd93a51df7a/dbterd/adapters/targets/dbml/dbml_test_relationship.py#L18C14-L18C20). This means we have to create two different directories in which to save the output files to. Also, the name 'output' is kind of generic. Finally, you can't create two seperate output files in the same directory because of this.

**Describe the solution you'd like**
Make the output file name dynamic and add an extra CLI argument to set a custom output file name. 

**Describe alternatives you've considered**
- Use directory per usecase.

**Comment by datnguye** [comment]
Thanks @Thootje for filing the request! 👍 

Yes I agree! It makes sense to customize the output file name. You're more than welcome to create a pull request for it too ❤️ . 

NOTE: Currently please expect for a low speed of releasing new feats/fixes as I need to dedicate much of time with family, but will try to come up with it as soon as possible.

Thanks 🙌

**Comment by Thootje** [comment]
I will take a look next week if I think I can do it myself. 👍

**Comment by datnguye** [comment]
Hey @Thootje not sure if you secure this change yet, sorry if yes. I have sometime today so just quickly make the change.

It should be published with v1.13 🏃

**Comment by datnguye** [comment]
It's now available in 1.13.0 with the latest docs [here](https://dbterd.datnguyen.de/1.13/nav/guide/cli-references.html#dbterd-run-output-file-name-ofn) 🎉

**Comment by Thootje** [comment]
Thanks a lot! I didn't have time last week unfortunately :(
