### ISSUE TITLE
[BUG] pinned version of dbt-artifacts-parser is not compatible with latest dbterd code

### ISSUE THREAD

**Issue by jacob-ketterer** [datnguye/dbterd#98]
**Describe the bug**
If using pip to update dbterd, a previous version of dbt-artifacts-parser may satisfy the pinned version but not have the latest manifest object versions defined (e.g. ManifestV11)

**To Reproduce**
Attempt to pip install --upgrade dbterd with an older version of dbt-artifacts-parser installed (could use v0.4.0 for example). Executing dbterd at this time will raise an error: 
`ModuleNotFoundError: No module named 'dbt_artifacts_parser.parsers.manifest.manifest_v11`

**Expected behavior**
required versions in the toml file could be more specific and cause pip to auto-update this dependency as needed when upgrading dbterd

**Desktop (please complete the following information):**
- OS: [macOS]
- Version [1.12.0]

**Comment by datnguye** [comment]
Hi @jacob-ketterer thanks for raising it!
For a resolution of this issue, I guess we can solve it with requiring the minimum dbt-artifact-parser version in pyproject.toml. Will do it in the next dbterd version and the patch of v1.12

**Comment by datnguye** [comment]
The latest doc site has been updated [here](https://dbterd.datnguyen.de/latest)

**Comment by datnguye** [comment]
Just to recap for the resolution of this from the docs

_It's highly recommended to update dbt-artifacts-parser to the latest version in order to support the newer dbt-core version which would cause to have the [new manifest / catalog json schema](https://schemas.getdbt.com/):_


```
pip install dbt-artifacts-parser --upgrade
```

**Comment by datnguye** [comment]
I am closing this issue now, but feel free to re-open it for any other suggestions of the resolution. Thank you!
